---
- name: Setup and deploy application
  hosts: all
  become: true
  tasks:
    - name: Install Python 3
      apt:
        name: python3
        state: present

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install boto3 using pip
      command: pip3 install boto3
